### ISSUE TITLE
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by BrandoZhang** [ThibaultGROUEIX/AtlasNet#32]
https://github.com/ThibaultGROUEIX/AtlasNet/blob/90fcd8a2650ef840ebc41319f435402fa1ba43ca/auxiliary/dataset.py#L110-L114

```
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/brando/anaconda3/envs/pytorch-atlasnet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/brando/anaconda3/envs/pytorch-atlasnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/brando/anaconda3/envs/pytorch-atlasnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./auxiliary/dataset.py", line 260, in __getitem__
    point_set = point_set[:, 0:3]
UnboundLocalError: local variable 'point_set' referenced before assignment
```
So what's your "weird error"? I tried to move the `point_set` assignment out of the for loop but it did not work.

**Comment by ThibaultGROUEIX** [comment]
Hi @BrandoZhang,
`point_set` is unassigned which means all the `try` cases fail : it shouldn't happen.
What exception do you get from the "except" part ?

The weird error I am referring to is that sometime `my_get_n_random_lines` fails because each line in the file doesn't have the same number of character. I hardcoded the number of consecutive characters to read [here](https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/auxiliary/my_utils.py#L40), for speed. Those cases are rare, and it can't happen 15 times in a row. i'll update this part in the next iteration of the code.
Best regards,
Thibault

**Comment by BrandoZhang** [comment]
Hi @ThibaultGROUEIX 
> The weird error I am referring to is that sometime `my_get_n_random_lines` fails because each line in the file doesn't have the same number of character. I hardcoded the number of consecutive characters to read [here](https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/auxiliary/my_utils.py#L40), for speed. Those cases are rare, and it can't happen 15 times in a row. i'll update this part in the next iteration of the code.

Yep, I notice this. I use the following codes to bypass the problem:

```
def get_n_random_vertices(path_to_file, n=5):
    mesh = pymesh.load_mesh(path_to_file)
    rv_raw = mesh.vertices[np.random.randint(mesh.vertices.shape[0], size=n), :].tolist()
    return [str(i).replace('[', '').replace(']', '').replace(',', '') for i in rv_raw]
```
To use this, you may need to install and import [pymesh](https://pymesh.readthedocs.io/en/latest/installation.html).

I just figured it out minutes ago to make sure the data structure is consistent. However, I think this process might be much slower than previous one (Especially for the return line, it is really dirty to format in this way).

Any advice?

**Comment by ThibaultGROUEIX** [comment]
Yes pymesh (or trimesh) makes this `very` slow, because the pointcloud sizes are large. that's why i used `my_get_n_random_lines` in the first place. it only reads 2000 consecutive random lines from the file, making things much faster.
I think you  have two options : 
- fix your usage of my_get_n_random_lines(it should work)
- rewrite the dataloader to put all the pointclouds in RAM (using pymesh to create a dataset tensor at the beginning of training). I think it should fit in memory. Just index the dataset tensor during training.
Best regards
